# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljHf-DZHUPCloWqUe8x0oaVSFN5_Bs9P
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np

d=pd.read_csv('train.csv')
d

d.isnull().sum()

d=d.drop(columns=['Cabin'])

d['Embarked']=d['Embarked'].fillna(d['Embarked'].mode()[0])

d['Age']=d['Age'].fillna(d['Age'].median())

d.isnull().sum()

d['Sex']=d['Sex'].map({'male':0, 'female':1})
d['Embarked']=d['Embarked'].astype('category').cat.codes



d

d.head()

d.info()

d.describe()

d.isnull().sum()

d['Sex'].value_counts()

d['Pclass'].value_counts()

d['Survived'].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=d, x='Survived')

What it shows:

-->Number of people who survived (1) vs not survived (0).

-->Gives an idea of class imbalance (more died than survived).

Insight:

-->Majority of passengers did not survive.

sns.countplot(data=d, x='Survived', hue='Sex')

What it shows:

-->Compare survival between males vs females.

-->Two bars for each group.

Insight:

-->Females survived much more than males.

-->This is because of the policy “women and children first”.

sns.countplot(data=d, x='Pclass', hue='Survived')

What it shows:

-->Survival count for all three passenger classes (1st, 2nd, 3rd).

-->Helps compare safety between classes.

Insight:

-->1st class passengers survived the most.

-->3rd class had the lowest survival.

sns.histplot(d['Age'], kde=True,bins=10)

What it shows:

-->Distribution of passenger ages.

-->KDE line shows smooth curve of density.

Insight:

-->Most passengers were between 20–40 years old.

-->Some children and older adults were present.

sns.boxplot(data=d, x='Survived', y='Age')

What it shows:

-->Age distribution of people who survived vs who did not.

-->Shows median, quartiles, outliers.

Insight:

-->Survivors were slightly younger on average.

-->Many older passengers did not survive.

sns.boxplot(data=d, x='Pclass', y='Fare')

What it shows:

-->How ticket fare varies in each class.

Insight:

-->1st class paid much higher fare.

-->Shows wide range of fares in upper class.

sns.scatterplot(data=d,x='Age',y='Fare',hue='Survived')

What it shows:

-->Relationship between age and fare.

-->Shows which points survived (color-coded).

Insight:

-->High-fare passengers (mostly 1st class) survived more.

-->Younger passengers had slightly better survival.

sns.heatmap(d[['Survived','Pclass','Age','SibSp','Parch','Fare']].corr(), annot=True,cmap='BuPu')

What it shows:

-->Numerical correlation between features.

-->Values between -1 and +1.

Insight:

-->Survival strongly correlates with:

-->Fare (+)

-->Pclass (–)

-->Pclass and Fare have strong negative correlation (expected).

sns.pairplot(d[['Survived','Pclass','Age','SibSp','Parch','Fare']],palette='BuPu')

What it shows:

-->Scatterplots for every pair of variables.

-->Diagonals show distribution of each variable.

Insight:

-->Helps identify:

-->Patterns

-->Clusters

-->Outliers

-->Shows clear grouping between Fare & Pclass.